### ISSUE TITLE
Font display issue for examples in Dash

### ISSUE THREAD

**Issue by ashmatadeen** [Moddus/tldr-python-dash-docset#3]
The command examples are not displaying in Dash:
![Screeshot of Dash tldr page](https://ashmatadeen.s3-eu-west-1.amazonaws.com/wp-content/uploads/2016/02/dash-tldr.png)

I'm running Dash v3.2.2 (190) on OS X 10.11.3

**Comment by Moddus** [comment]
Hi,
do you build the docset by yourself oder do you use my "user contributed" docset ? If you use my "user contributed" docset you should use version 0.0.2.11 or in a few hours 0.0.2.12.
I'm also running Dash v3.2.2 on OS X 10.11.3 and both docset versions running as expected.

Greetz,
Moddus

**Comment by ashmatadeen** [comment]
I used the "user contributed" docset. I've updated to 0.0.2.12 but the commands are still not displaying. It's odd because the text is there, if select a chunk of text and then paste it into a text editor, I can see the examples are there, they just don't display within Dash.

**Comment by ashmatadeen** [comment]
Turned out the font Source Code Pro was corrupt on my system. I've reinstalled the font and all is well again. Thanks to @Kapeli for helping troubleshoot.
